sudo: required
service:
  - docker

before_install:
  - docker build -t vijacob/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vijacob/docker-react npm run test -- --coverage

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: docker-react
#  env: "Docker-env"
#  bucket_name: "docker"
#  on:
#    branch: master
